#!/bin/sh
export MICROSOFT_REALM=
export MICROSOFT_CLIENT_ID=
export MICROSOFT_CLIENT_SECRET=
export MICROSOFT_APP_ID=
export MICROSOFT_APP_PASSWORD=
export AUTHBOT_CALLBACKHOST=
export AUTHBOT_STRATEGY=
